/* 
 * Copyright (C) 2017 Raffaele Francesco Mancino
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.raffaele.agrigest.view;

import com.raffaele.agrigest.AgriGest;
import javax.swing.JPanel;

/**
 *
 * @author Raffaele Francesco Mancino
 */
public class BaseWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form BaseWindow
     */
    public BaseWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBarPlotAdd = new javax.swing.JMenuBar();
        jMenuCompany = new javax.swing.JMenu();
        jMenuItemHome = new javax.swing.JMenuItem();
        jMenuItemReLogin = new javax.swing.JMenuItem();
        jMenuField = new javax.swing.JMenu();
        jMenuItemPlotAdd = new javax.swing.JMenuItem();
        jMenuItemPlotDel = new javax.swing.JMenuItem();
        jMenuWarehouse = new javax.swing.JMenu();
        jMenuMonitoring = new javax.swing.JMenu();
        jMenuPrint = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgriGest");

        jMenuCompany.setText("Azienda");
        jMenuCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCompanyMouseClicked(evt);
            }
        });
        jMenuCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompanyActionPerformed(evt);
            }
        });

        jMenuItemHome.setText("Home");
        jMenuItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeActionPerformed(evt);
            }
        });
        jMenuCompany.add(jMenuItemHome);

        jMenuItemReLogin.setText("Re Login");
        jMenuItemReLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReLoginActionPerformed(evt);
            }
        });
        jMenuCompany.add(jMenuItemReLogin);

        jMenuBarPlotAdd.add(jMenuCompany);

        jMenuField.setText("Campi");
        jMenuField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenuField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFieldMouseClicked(evt);
            }
        });

        jMenuItemPlotAdd.setText("Aggiungi Appezzamento");
        jMenuItemPlotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlotAddActionPerformed(evt);
            }
        });
        jMenuField.add(jMenuItemPlotAdd);

        jMenuItemPlotDel.setText("Rimuovi Appezzamento");
        jMenuItemPlotDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemPlotDelMouseClicked(evt);
            }
        });
        jMenuItemPlotDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlotDelActionPerformed(evt);
            }
        });
        jMenuField.add(jMenuItemPlotDel);

        jMenuBarPlotAdd.add(jMenuField);

        jMenuWarehouse.setText("Magazzini");
        jMenuBarPlotAdd.add(jMenuWarehouse);

        jMenuMonitoring.setText("Monitoraggi");
        jMenuBarPlotAdd.add(jMenuMonitoring);

        jMenuPrint.setText("Stampe");
        jMenuBarPlotAdd.add(jMenuPrint);

        setJMenuBar(jMenuBarPlotAdd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuFieldAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFieldAncestorAdded

    private void jMenuItemPlotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlotAddActionPerformed
        AgriGest.appController.startPlotAdd();
    }//GEN-LAST:event_jMenuItemPlotAddActionPerformed

    private void jMenuCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCompanyMouseClicked
        
    }//GEN-LAST:event_jMenuCompanyMouseClicked

    private void jMenuItemReLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReLoginActionPerformed
        AgriGest.login();
    }//GEN-LAST:event_jMenuItemReLoginActionPerformed

    private void jMenuItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeActionPerformed
        AgriGest.appController.startHome();
    }//GEN-LAST:event_jMenuItemHomeActionPerformed

    private void jMenuCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCompanyActionPerformed

    private void jMenuFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFieldMouseClicked
        
    }//GEN-LAST:event_jMenuFieldMouseClicked

    private void jMenuItemPlotDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemPlotDelMouseClicked
       
    }//GEN-LAST:event_jMenuItemPlotDelMouseClicked

    private void jMenuItemPlotDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlotDelActionPerformed
         AgriGest.appController.startPlotDel();
    }//GEN-LAST:event_jMenuItemPlotDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarPlotAdd;
    private javax.swing.JMenu jMenuCompany;
    private javax.swing.JMenu jMenuField;
    private javax.swing.JMenuItem jMenuItemHome;
    private javax.swing.JMenuItem jMenuItemPlotAdd;
    private javax.swing.JMenuItem jMenuItemPlotDel;
    private javax.swing.JMenuItem jMenuItemReLogin;
    private javax.swing.JMenu jMenuMonitoring;
    private javax.swing.JMenu jMenuPrint;
    private javax.swing.JMenu jMenuWarehouse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
